# Generated by Django 3.2.7 on 2021-10-06 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='adminManagement',
        ),
    ]
