# Generated by Django 3.2.7 on 2021-10-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0007_student_gpa'),
    ]

    operations = [
        migrations.CreateModel(
            name='instructor',
            fields=[
                ('pw', models.CharField(auto_created='123456', max_length=12)),
                ('iid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('insName', models.CharField(max_length=36)),
                ('username', models.CharField(max_length=8)),
                ('gender', models.CharField(max_length=1)),
                ('email', models.CharField(max_length=64)),
                ('cp_num', models.IntegerField(default=0)),
                ('class_teaching', models.IntegerField(default=0)),
                ('curStatus', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'instructor',
            },
        ),
    ]
