# Generated by Django 3.2.7 on 2021-10-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0009_stuapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='insApplication',
            fields=[
                ('stateid', models.IntegerField(primary_key=True, serialize=False)),
                ('insName', models.CharField(max_length=36)),
                ('gender', models.CharField(max_length=1)),
                ('email', models.CharField(max_length=64)),
                ('curStatus', models.SmallIntegerField(default=0)),
                ('info', models.CharField(default='None', max_length=36)),
                ('feedback', models.CharField(default='None', max_length=36)),
            ],
            options={
                'db_table': 'insApplication',
            },
        ),
        migrations.RenameField(
            model_name='stuapplication',
            old_name='insName',
            new_name='stuName',
        ),
    ]
