# Generated by Django 3.2.7 on 2021-10-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0011_auto_20211013_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='start_time',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='cid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='course',
            table='course',
        ),
    ]
