# Generated by Django 3.2.7 on 2021-10-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0012_auto_20211014_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='insName',
        ),
        migrations.AddField(
            model_name='course',
            name='iid',
            field=models.IntegerField(default=0),
        ),
    ]
